global:
  scrape_interval: 10s

rule_files:
  - "rules/memory.yml"

scrape_configs:
 - job_name: prometheus
   scrape_interval: 60s
   static_configs:
    - targets:
       - prometheus:9090

 - job_name: node
   scrape_interval: 60s
   static_configs:
    - targets: 
       - node-exporter:9100

 - job_name: traefik
   scrape_interval: 30s
   static_configs:
    - targets:
       - traefik:8099

 - job_name: adguard
   scrape_interval: 60s
   static_configs:
    - targets: 
       - adguardhome-metrics:9618

 - job_name: watchtower
   scrape_interval: 300s
   static_configs:
    - targets:
       - watchtower:8080
   metrics_path: /v1/metrics
   bearer_token: prom

 - job_name: cadvisor
   scrape_interval: 30s
   scrape_timeout: 10s
   static_configs:
    - targets:
       - cadvisor:8080
   metric_relabel_configs:
    - source_labels: [__name__]
      regex: 'container_(memory_usage_bytes|memory_cache|memory_rss|cpu_usage_seconds_total|network_.*_bytes_total|fs_.*_bytes)'
      action: keep
    - regex: 'container_label_.*'
      action: labeldrop
    - regex: 'image'
      action: labeldrop

 - job_name: restic-exporter
   scrape_interval: 300s
   static_configs:
    - targets:
       - restic-exporter:8001
        
