global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: node
   static_configs:
    - targets: 
       - node-exporter:9100
 - job_name: traefik
   static_configs:
    - targets:
       - traefik:8099
 - job_name: rclone
   static_configs:
    - targets: 
       - 192.168.1.200:5572
 - job_name: adguard
   static_configs:
    - targets: 
       - adguardhome-metrics:9618
 - job_name: watchtower
   static_configs:
    - targets:
       - watchtower:8080
   metrics_path: /v1/metrics
   bearer_token: prom
 - job_name: cadvisor
   scrape_interval: 5s
   static_configs:
    - targets:
       - cadvisor:8080
 - job_name: duplicati
   honor_labels: true
   static_configs:
    - targets: 
       - duplicati-exporter:5000
